apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whereabouts
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amrbaraka/helm-charts.git
    targetRevision: master
    path: ./whereabouts-test-chart/whereabouts-test-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:    
    automated:
      prune: true            # Optional: Prune resources not defined in Git
      selfHeal: true          # Optional: Automatically apply any out-of-sync changes
