apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  # Option to automatically create the namespace if it doesn't exist
    automated:
      prune: true            # Optional: Prune resources not defined in Git
      selfHeal: true          # Optional: Automatically apply any out-of-sync changes
