apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amrbaraka/testing.git
    targetRevision: HEAD
    path: ./nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:    
    automated:
      prune: true            # Optional: Prune resources not defined in Git
      selfHeal: true          # Optional: Automatically apply any out-of-sync changes
