apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: multus
    repoURL: https://amrbaraka.github.io/helm-charts/
    targetRevision: 0.1.2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:    
    automated:
      prune: true            # Optional: Prune resources not defined in Git
      selfHeal: true          # Optional: Automatically apply any out-of-sync changes
